---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ENVS475

Course materials for ENVS475 at Colorado Mesa University

## About

This repository will serve as the unofficial collection of materials for
ENVS475 Experimental Analysis and Design at Colorado Mesa University.

The goal of this website is to create a central repository for students
registered in the class as well as other interested persons to access
all course materials. If you have any issues or problems, feel free to
contact me at jpomeranz [at] coloradomesa [dot] edu

## Installation

You can install the development version of ENVS475 from
[GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Jpomz/ENVS475")
```

## CMU Students  

All course materials will be available on this website. Course communications and assignment submissions will occur through our D2L page. 

## Self-guided students  

The materials presented here are free for your use. Each week there is generally one lecture, lab, and homework assignment, all numbered by the week of the course. Exams are in week 8 and 15 (no materials on the website). All data objects will eventually be included in the `ENVS475` package and can be loaded into your RStudio session by running `data("data-object-name")`. In the meantime, you can download the data objects individually from the [repository hosted on GitHub.](https://github.com/Jpomz/ENVS475/tree/master/data) 

## Educators  

Materials included in this course is purposefully made available to anyone who finds it useful. Users are free to use, adapt, distribute, display, and communicate these materials freely. If you have any questions you can reach out to me. Likewise, if you are going to use or modify these materials in your own classes or labs, please let me know. Tracking use of these materials is a helpful non-standard metric for tenure and promotion in my position. 

## Acknowledgements

I thank the maintainers and developers of the R ecosystem for fostering
and encouraging an open science framework, as well as all the R
practitioners around the world which make their code freely and openly
available to everyone.

In particular, the development of this course was strongly influenced by
materials from - Clark Rushing
<https://rushinglab.github.io/FANR6750/index.html> - Ethan White and
others <https://datacarpentry.org/semester-biology/> and - Mark
Scheuerell <https://qerm514.github.io/website/index.html>.



