---
title: "Schedule"
subtitle: "ENVS475"
author: "Spring 2024"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE, warning = FALSE, message = FALSE,
  comment = "#>"
)

options(rmarkdown.html_vignette.check_title = FALSE)
#source(here::here("R/MWF.R"))
```


### Subject to change  

```{r schedule, echo = FALSE}
library(kableExtra)

schedule <- data.frame(WK = c("1",
                              "2",
                              "3", 
                              "4",
                              "5", 
                              "6", 
                              "7", 
                              "8",
                              "Spring Break", 
                              "9", 
                              "10", 
                              "11", 
                              "12",
                              "13", 
                              "14", 
                              "15", 
                              "Finals"),
                       #Day = c(rep(c("M", "W", "F", ""), 17)),
                       #Week = MWF(first.day = "2024/01/22", last.day = "2024/05/13"),
                       Lecture = c(
                         "Course introduction",#1
                         "Introduction to R Lab",#2
                         "Basic Statistics", #3
                         "Lab 04a: dplyr", # 4
                         "Estimation", #5
                         "Intro to Models", #6
                         "t-tests", #7
                         "Exam 1", #8 exam 1 
                         "", # Spring break 
                         "RMarkdown", #9
                         "ANOVA", # 10
                         "Factorial ANOVA", #11
                         "2-way ANOVA", #12
                         "Linear Regression", #13    
                         "ANCOVA", #14
                         "Exam 2", #15
                         "Monday 3-4:50 pm" #16
                       ),
                       Reading = c(
                         "Hector Ch. 1, 2, 20",#1
                         "Hector Ch. 1, 2, 20",#2
                         "Hector Ch. 5", #3
                         "R4DS Ch. 3", # 4
                         "Hector Ch. 3, 5, 10",#5
                         "Hector Ch. 6", #6
                         "Hector Ch. 6, 9", #7
                         "None", #8 exam 1 
                         "None", # Spring break 
                         "Hector Ch. 4; R4DS Ch. 3", #9
                         "Hector Ch. 11, 12", # 10
                         "Hector Ch. 11, 12", #11
                         "Hector Ch. 11, 12", #12
                         "Hector Ch. 7", #13    
                         "Hector Ch. 14, 15", #14
                         "None", #15
                         "None" #16
                       ),
                       Lab = c(
                         "Lab 01: RStudio Projects",#1
                         "Lab 02: Introduction to R",#2
                         "Lab 03: Normal Distributions", #3
                         "Lab 04b: ggplot2", # 4
                         "Lab 05: Estimation", #5
                         "Lab 06: Intro to Models", #6
                         "Lab 07: t-tests", #7
                         "No Lab: Exam 1", #8 exam 1 
                         "", # Spring break 
                         "Lab 09: Rmarkdown", #9
                         "Lab 10: ANOVA", # 10
                         "Lab 11: Factorial ANOVA", #11
                         "Lab 12: 2-way ANOVA", #12
                         "Lab 13: Linear Regression", #13    
                         "Lab 14: ANCOVA", #14
                         "No Lab: Exam 2", #15
                         "" #16
                         ),
                       Homework = c(
                         "HW 01: Computer and Project setup",#1
                         "HW 02: Introduction to R",#2
                         "HW 03: Normal Distributions", #3
                         "HW 04: dplyr + ggplot2", # 4
                         "HW 05: Estimation", #5
                         "HW 06: Intro to Models", #6
                         "HW 07: t-tests", #7
                         "Exam 1", #8 exam 1 
                         "", # Spring break 
                         "HW 09: Rmarkdown", #9
                         "HW 10: ANOVA", # 10
                         "HW 11: Factorial ANOVA", #11
                         "HW 12: 2-way ANOVA", #12
                         "HW 13: Linear Regression", #13    
                         "HW 14: ANCOVA", #14
                         "Exam 2", #15
                         "" #16),
                       ))

schedule %>%
  kable("html", col.names = c("Week", "Monday (Lecture)", "Wednesday (Lab)", "Friday (Homework"), align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE)

```

\* = Graded assignment
