---
title: "Syllabus"
subtitle: "ENVS475"
author: "Spring 2024"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Syllabus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE, warning = FALSE, message = FALSE,
  comment = "#>"
)
```

### Subject to change  

## Instructor Information

Instructor Name: Dr. Justin Pomeranz

Email: <jpomeranz@coloradomesa.edu>

Office: Wubben 230E

Office Hours: MWF 11-11:50 am, or by appointment

## Course Information

Course Title: Experimental Design and Analysis, ENVS 475

Course Delivery Method: Campus

Class Time: Monday, Wednesday, and Friday 2-2:50 pm

Classroom: Wubben 245

Prerequisites: ENVS 204 or ENVS 221, STAT 200

Drop Date: April 8th. 2024

Lecture Hours: 3

# Course Overview 

## COURSE DESCRIPTION 

This course will give you practical information on designing experiments and analyzing data in various areas of environmental science. We will cover experimental design, data curation and preparation, and statistical analyses. We also cover many different types of statistical tests using data from various areas of environmental science. When using these tests you need to keep in mind the earlier things you learned. In addition, you’ll learn how to use the R statistical programming language.

This course generally follows the "I do, we do, you do" format. A typical week will consist of a lecture introducing a new concept or topic on Mondays (I do), a lab or class activity on that topic on Wednesdays (we do), and Friday will be open to ask questions and to work on the weekly homework assignment (You do, but I'm here to help).

## PROGRAM STUDENT LEARNING OUTCOMES 

1) Demonstrate the ability to design an environmental study. (Quantitative skills, critical thinking skills), and

2) Demonstrate the ability to analyze quantitative environmental data, effectively translate data into graphs or tables, and interpret the results. (Quantitative skills, critical thinking skills)

## COURSE COMMUNICATION

All communication in this course will be made via your CMU email account and through this D2L page. Please check your CMU email and the D2L page regularly.

When sending me an email, please include the course number in the subject line as well as a brief subject (example: ENVS 475 - question on HW 3). Check your email regularly throughout the semester. I will do my best to respond within 2 business days.

# Course Requirements 

## REQUIRED TEXTS AND SUPPLIES (ALL FREE) 

### TEXTS: 

**The New Statistics with R** by Andy Hector.
Available through the CMU Library 

**R for Data Science** by Hadley Wickham and Garrett Grolemund 

Available for [free online](https://r4ds.had.co.nz/index.html) 

## STATISTICAL SOFTWARE 


All the software required for this course is available on the ENVS laptops in the classroom. Likewise, computers in the WS building and library should have software programs installed. 

If you own a personal computer (laptop or desktop), you are strongly encouraged to download the programs so you can work on them at home. If you have a laptop, please bring it to class whenever you are able.

### R and RStudio 

For instructions, [click here](https://jpomz.github.io/ENVS396-FA-2023/computer-setup/). Please note that this is a 2-step process. You need to install R *before* you install RStudio.

Please install both of these ASAP

Get in touch with me if you have any problems 

### Excel 
You should have access to Microsoft programs through your CMU account. Additionally, free resources such as Google Sheets should have most or all of the functionality required.

If you use Google sheets, make sure you can export the file as a .csv

## Why R? 

R is a free, open source language which is widely used in the fields of Environmental Science, Ecology and beyond. R runs on all platforms (Windows, Mac, Linux) and is one solution to the [replication crisis](https://en.wikipedia.org/wiki/Replication_crisis) currently happening in science. Furthermore, R is an in-demand skill which will make you competitive on the job market.

## LESSON/INSTRUCTIONAL MATERIALS
I have attempted to make this course as hands-on as possible. I have found that the best way to learn coding and statistics is to do coding and statistics. Further, these tasks are easier to do when you have someone around you can ask questions of when you inevitably run into problems or errors. This is true when making calculations by hand, but is even more so when using analysis software. In order to reserve as much class time for working on problems and homework assignments, it is vital that you read the assigned book chapters and lectures before coming to class.

Make sure to reference the class schedule regularly to ensure you know what we will be covering on that day. In general, we will spend 1-3 class periods on a given topic. I will usually begin class with a brief introduction or review of the material we are working on, with the majority of our in-class time being dedicated to working through problems and homework assignments.

## Course Policies 

### METHODS OF EVALUATION/GRADING POLICY 

Grade Distribution Percentage

Graded Homework (13) 60%	

Take Home Exams (2) 40%	


### Grading Scale 

A = 89.5 - 100%

B = 79.5 - 89.4%

C = 69.5 - 79.4%

D = 59.5 - 69.4%

F = < 59.4%

## ASSIGNMENT EXPECTATIONS 

### Homework 

*Homework*: There will be weekly homework assignments.  Homework assignments need to be turned in on an individual basis, but you are allowed (and encouraged!) to work on them in groups. Homework assignments will all be turned in via the appropriate links in D2L. Homework is assigned weekly on Mondays and due the following Friday, with a grace period of 2 days (i.e., as long as homework is submitted by Sunday night, you do not need to request an extension). Homework turned in after the grace period will be docked 50%, and late work will not be accepted after 5 days late (i.e. Wednesday). Solutions to homework will generally be posted on the Wednesday after they are due (i.e., after the late submission window closes).

### Homework Grade Rubric 

Produces the correct answer using the requested approach: 100%

Generally uses the right approach, but a minor mistake results in an incorrect answer: 90%

Attempts to solve the problem and makes some progress using the core concept: 75% 

Incomplete assignment submitted; OR complete assignment submitted after 2-day grace period: 50%

Answer demonstrates a lack of understanding of the core concept; OR mostly incomplete: 0%

Solutions to assignments will be posted on D2L and/or will be gone over in class. Solutions will generally be posted on Wednesdays, after the late submission window closes.

### Exams 

*Exams*: There will be two take-home exams in this course. You are allowed to reference your text book, notes, homework assignments, statistical software, the internet, etc. You are also welcome to work on them in groups, and to ask me questions. However, much like the homework assignments, you need to submit individual exams and the questions need to be answered in your own words. Exams will generally be due one week after they are assigned. Late submissions will follow the same penalty formula as homework described above (late = -50%, will not be accepted after one week late).&nbsp;


## ATTENDANCE POLICY

I expect that you come to class having completed the reading assignments, homework, etc. and ready to participate and engage with the lecture material, as well as work on the problem sets and homework assignments, and to ask me questions. However, I will not be taking attendance in this class. All the learning materials for this course are available on the website and D2L. If you miss a day, it is your responsibility to catch up on what you missed and go over the learning materials.

If you are sick or have excused absences, please get in touch with me ASAP to make arrangements to make up any assignments or due dates that you may miss.

## SUPPLEMENTAL HELP 

In coordination with Educational Access Services, reasonable accommodations will be provided for qualified students with disabilities. Students should contact Educational Access Services at 970-248-1856 or Houston Hall, Suite 108 as soon as possible. Please visit <https://www.coloradomesa.edu/educational-access> for additional information. If you wish to discuss academic accommodations, please contact me as soon as possible.


## MINIMUM TECHNOLOGY AND SKILLS REQUIREMENT

You will need basic computer skills and should be comfortable using a word processing program, browsing for files, and copying and pasting between programs. You will need a computer that connects to high-speed internet. Your username and password are required for access. If you do not own a computer or if your computer malfunctions during the term, you will be expected to identify a computer to use. Technology issues are not an excuse for missed or late work.

To have the best learning experience possible, please be sure you have access to Colorado Mesa University's recommended technology.
